const data = [
  {
    name: "abillion",
    image: "abillion.jpg-glj.jpg",
    date: "22 October 2020",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "1969 Restaurant",
    restID: 5599388,
    comments: 842,
    rating: "1.0",
    price: 156,
    stock: 32,
  },
  {
    name: "alejandro duarte",
    image: "alejandro-duarte.jpg-ci2.jpg",
    date: "23 August 2022",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "14th Street Restaurant",
    restID: 6875441,
    comments: 1395,
    rating: "3.1",
    price: 112,
    stock: 12,
  },
  {
    name: "andriyko podilnyk",
    image: "andriyko-podilnyk-9282f.jpg",
    date: "1 June 2020",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Tai Zu Restaurant",
    restID: 5189874,
    comments: 1195,
    rating: "1.4",
    price: 34,
    stock: 10,
  },
  {
    name: "anna peipina",
    image: "anna-peipina-2j9hu.jpg",
    date: "25 February 2021",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "wild rice Restaurant",
    restID: 2377464,
    comments: 1503,
    rating: "4.0",
    price: 29,
    stock: 12,
  },
  {
    name: "artur rutkowski",
    image: "artur-rutkowski-tpm8d.jpg",
    date: "24 June 2018",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "1969 Restaurant",
    restID: 3092533,
    comments: 1023,
    rating: "1.7",
    price: 157,
    stock: 13,
  },
  {
    name: "bianca berg",
    image: "bianca-berg-33zco.jpg",
    date: "3 August 2021",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Nandos Restaurant",
    restID: 5495195,
    comments: 1494,
    rating: "0.7",
    price: 109,
    stock: 14,
  },
  {
    name: "bruna branco",
    image: "bruna-branco-e4pgf.jpg",
    date: "30 July 2018",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Grill Restaurant",
    restID: 6319060,
    comments: 1328,
    rating: "4.5",
    price: 145,
    stock: 10,
  },
  {
    name: "cristina anne",
    image: "cristina-anne-b2jr2.jpg",
    date: "1 June 2018",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Tai Zu Restaurant",
    restID: 1145207,
    comments: 828,
    rating: "1.3",
    price: 137,
    stock: 10,
  },
  {
    name: "ella olsson",
    image: "ella-olsson-o3p9t.jpg",
    date: "16 October 2018",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "1969 Restaurant",
    restID: 6120639,
    comments: 1269,
    rating: "0.9",
    price: 63,
    stock: 10,
  },
  {
    name: "eriks abzinovs",
    image: "eriks-abzinovs-1lqo4.jpg",
    date: "1 February 2022",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "China Town Restaurant",
    restID: 4444400,
    comments: 1838,
    rating: "0.5",
    price: 193,
    stock: 10,
  },
  {
    name: "ivan torres",
    image: "ivan-torres.jpg-jcq.jpg",
    date: "12 February 2018",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Nandos Restaurant",
    restID: 5974456,
    comments: 1287,
    rating: "2.9",
    price: 39,
    stock: 67,
  },
  {
    name: "joseph gonzalez",
    image: "joseph-gonzalez-uc34j.jpg",
    date: "27 July 2022",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Kabul Restaurant",
    restID: 9386854,
    comments: 598,
    rating: "4.1",
    price: 143,
    stock: 23,
  },
  {
    name: "keriliwi Mkvo4z",
    image: "keriliwi-Mkvo4z-qym08.jpg",
    date: "19 August 2019",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Grill Restaurant",
    restID: 7621726,
    comments: 1995,
    rating: "0.3",
    price: 95,
    stock: 42,
  },
  {
    name: "keriliwi s0mf00gThvU",
    image: "keriliwi-s0mf00gThvU-mrc0x.jpg",
    date: "25 January 2019",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Spring Salt Restaurant",
    restID: 2305713,
    comments: 576,
    rating: "1.2",
    price: 14,
    stock: 32,
  },
  {
    name: "lidya nada",
    image: "lidya-nada-3o5dq.jpg",
    date: "4 October 2019",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "YUM Restaurant",
    restID: 7473010,
    comments: 950,
    rating: "4.1",
    price: 66,
    stock: 10,
  },
  {
    name: "mae mu",
    image: "mae-mu-16hrn.jpg",
    date: "4 April 2020",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Nadia Cafe Restaurant",
    restID: 6751977,
    comments: 1041,
    rating: "4.3",
    price: 113,
    stock: 6,
  },
  {
    name: "mae mu",
    image: "mae-mu-rs2m7.jpg",
    date: "2 June 2018",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Serena Restaurant",
    restID: 2901065,
    comments: 882,
    rating: "4.5",
    price: 71,
    stock: 76,
  },
  {
    name: "mae mu",
    image: "mae-mu-hj3mi.jpg",
    date: "21 October 2019",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "wild rice Restaurant",
    restID: 6296527,
    comments: 1139,
    rating: "0.5",
    price: 153,
    stock: 3,
  },
  {
    name: "mae mu",
    image: "mae-mu-23o3n.jpg",
    date: "1 April 2017",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "HowDay Restaurant",
    restID: 7730187,
    comments: 1405,
    rating: "3.8",
    price: 157,
    stock: 10,
  },
  {
    name: "mae mu",
    image: "mae-mu-xp2sj.jpg",
    date: "20 April 2020",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Tuscany Courtyard Restaurant",
    restID: 6943710,
    comments: 1285,
    rating: "1.8",
    price: 132,
    stock: 7,
  },
  {
    name: "mae mu",
    image: "mae-mu-0ott9.jpg",
    date: "2 January 2018",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "14th Street Restaurant",
    restID: 5726676,
    comments: 546,
    rating: "3.1",
    price: 26,
    stock: 3,
  },
  {
    name: "mae mu",
    image: "mae-mu-ybk5y.jpg",
    date: "7 January 2021",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "HowDay Restaurant",
    restID: 6176347,
    comments: 1773,
    rating: "4.6",
    price: 57,
    stock: 6,
  },
  {
    name: "mae mu",
    image: "mae-mu-pimio.jpg",
    date: "17 February 2021",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Tai Zu Restaurant",
    restID: 4483845,
    comments: 1343,
    rating: "4.5",
    price: 34,
    stock: 14,
  },
  {
    name: "mae mu",
    image: "mae-mu-1mujt.jpg",
    date: "28 October 2020",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Siena Restaurant",
    restID: 2065657,
    comments: 1672,
    rating: "2.0",
    price: 59,
    stock: 18,
  },
  {
    name: "markus spiske",
    image: "markus-spiske-dn9ni.jpg",
    date: "2 April 2021",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "China Town Restaurant",
    restID: 4901576,
    comments: 1671,
    rating: "0.2",
    price: 121,
    stock: 11,
  },
  {
    name: "masimo grabar",
    image: "masimo-grabar-oj63j.jpg",
    date: "19 February 2018",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Grill Restaurant",
    restID: 9783380,
    comments: 1974,
    rating: "2.8",
    price: 73,
    stock: 13,
  },
  {
    name: "pierre bamin",
    image: "pierre-bamin-3vi1v.jpg",
    date: "13 October 2019",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Khyber Restaurant",
    restID: 9177849,
    comments: 772,
    rating: "3.0",
    price: 52,
    stock: 14,
  },
  {
    name: "pierre bamin",
    image: "pierre-bamin-9cdug.jpg",
    date: "28 August 2019",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Spring Salt Restaurant",
    restID: 7541635,
    comments: 785,
    rating: "1.0",
    price: 168,
    stock: 16,
  },
  {
    name: "pranjall kumar",
    image: "pranjall-kumar-amcsw.jpg",
    date: "18 April 2019",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "HowDay Restaurant",
    restID: 1679885,
    comments: 1271,
    rating: "2.0",
    price: 146,
    stock: 17,
  },
  {
    name: "raimond klavins",
    image: "raimond-klavins-s75g5.jpg",
    date: "18 November 2020",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "HowDay Restaurant",
    restID: 2910941,
    comments: 1380,
    rating: "0.1",
    price: 126,
    stock: 19,
  },
  {
    name: "sam moghadam",
    image: "sam-moghadam-ar131.jpg",
    date: "1 September 2020",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "YUM Restaurant",
    restID: 3058278,
    comments: 1524,
    rating: "2.4",
    price: 168,
    stock: 12,
  },
  {
    name: "sam moghadam",
    image: "sam-moghadam-cndhr.jpg",
    date: "10 February 2021",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Serena Restaurant",
    restID: 2441916,
    comments: 889,
    rating: "2.0",
    price: 197,
    stock: 13,
  },
  {
    name: "sam moghadam",
    image: "sam-moghadam-a2vzv.jpg",
    date: "3 April 2018",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Spring Salt Restaurant",
    restID: 3894949,
    comments: 1420,
    rating: "0.6",
    price: 38,
    stock: 10,
  },
  {
    name: "sara dubler",
    image: "sara-dubler-i4z0t.jpg",
    date: "5 August 2018",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",

    restaurant: "wild rice Restaurant",
    restID: 5327897,
    comments: 674,
    rating: "4.1",
    price: 158,
    stock: 13,
  },
  {
    name: "saundarya srinivasan",
    image: "saundarya-srinivasan-2ebwk.jpg",
    date: "18 April 2018",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Tai Zu Restaurant",
    restID: 1226646,
    comments: 1710,
    rating: "2.2",
    price: 126,
    stock: 12,
  },
  {
    name: "yoori koo",
    image: "yoori-koo-c5oxn.jpg",
    date: "4 May 2019",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quo qui distinctio provident repellendus beatae fugiat eum minus vitae delectus nulla, officiis obcaecati corporis tenetur, soluta voluptatum? Vitae, et voluptate.",
    restaurant: "Grill Restaurant",
    restID: 5633367,
    comments: 774,
    rating: "1.9",
    price: 22,
    stock: 15,
  },
];
export default data;
